/** Design tokens — CSS variables so inline styles follow light/dark theme.
 * Brand hues stay hex so alpha suffixes like T.blue + "22" keep working. */
export const T = {
  pageBg: 'var(--color-page-bg)',
  cardBg: 'var(--color-card-bg)',
  cardBorder: 'var(--color-card-border)',
  inputBg: 'var(--color-input-bg)',
  inputBorder: 'var(--color-input-border)',
  mutedBg: 'var(--color-muted-bg)',
  elevatedBg: 'var(--color-elevated-bg)',
  rowHover: 'var(--color-row-hover)',
  rowSelected: 'var(--color-row-selected)',
  navBg: 'var(--color-nav-bg)',
  navBorder: 'var(--color-nav-border)',
  navText: 'var(--color-nav-text)',
  accentBg: 'var(--color-accent)',
  t1: 'var(--color-t1)',
  t2: 'var(--color-t2)',
  t3: 'var(--color-t3)',
  t4: 'var(--color-t4)',
  t5: 'var(--color-t5)',
  purple: '#7c3aed',
  purpleL: 'var(--color-brand-purple-light)',
  blue: '#2563eb',
  blueL: 'var(--color-brand-blue-light)',
  green: '#16a34a',
  greenL: 'var(--color-brand-green-light)',
  amber: '#d97706',
  amberL: 'var(--color-brand-amber-light)',
  red: '#dc2626',
  redL: 'var(--color-brand-red-light)',
  cyan: '#0891b2',
  cyanL: 'var(--color-brand-cyan-light)',
  orange: '#ea580c',
} as const
