import type {
  AgencyClient,
  AgencyProspect,
  AgencyTalent,
  AgencyTask,
  Appointment,
  CalendarEvent,
  ChecklistItem,
  ClientInvoice,
  Disbursement,
  EscrowDeposit,
  ExpensePayoutLog,
  MessageThread,
  ProspectContract,
  RetainerPlan,
  SupportTicket,
  Vendor,
} from '@/types/agency'
import {
  makeTextContractDocument,
  REPRESENTATION_AGREEMENT_TEXT,
} from '@/lib/representation-agreement'
import { seedProfilePhoto } from '@/lib/profile-photo'

/** Scenario: Sarah (agent) · Nike (client) · Maya (talent) · $10k shoot @ 20% commission */

function seededContract(input: {
  id: string
  title: string
  status: ProspectContract['status']
  startDate: string
  endDate?: string | null
  representationType?: ProspectContract['representationType']
  termLengthYears?: ProspectContract['termLengthYears']
  talentName: string
}): ProspectContract {
  const termNote = input.endDate
    ? `Term: ${input.startDate} through ${input.endDate}.`
    : `Term begins ${input.startDate} (open-ended).`
  const body = `${REPRESENTATION_AGREEMENT_TEXT}

---
Talent: ${input.talentName}
${termNote}
Representation: ${input.representationType || 'exclusive'}
`
  return {
    id: input.id,
    title: input.title,
    status: input.status,
    startDate: input.startDate,
    endDate: input.endDate ?? null,
    representationType: input.representationType,
    termLengthYears: input.termLengthYears,
    uploadedAt: `${input.startDate}T12:00:00Z`,
    document: makeTextContractDocument(
      `${input.title.replace(/\s+/g, '_')}.txt`,
      body,
    ),
  }
}

export const AGENCY_STAFF = {
  id: 'staff_sarah',
  name: 'Sarah Chen',
  title: 'Senior Booking Agent',
  email: 'sarah.chen@nzinga.co',
}

/** Agents who can be assigned support tickets (excludes director & ops). */
export const AGENCY_TICKET_AGENTS: { id: string; name: string; title: string }[] = [
  AGENCY_STAFF,
  { id: 'u1', name: 'Jordan Hayes', title: 'Talent Scout' },
  { id: 'u2', name: 'Marcus Bell', title: 'Team 1 Lead' },
  { id: 'u4', name: 'Devon Cruz', title: 'Team 2 Lead' },
  { id: 'u6', name: 'Alexis Grant', title: 'Success Manager' },
]

export const AGENCY_CLIENTS_SEED: AgencyClient[] = [
  {
    id: 'client_nike',
    name: 'Nike',
    type: 'Production Brand',
    contact: 'Jordan Hale — Production',
    email: 'production@nike.example',
  },
]

export const AGENCY_TALENT_SEED: AgencyTalent[] = [
  {
    id: 'talent_maya',
    accountId: 'NZG-200101',
    name: 'Maya Rivera',
    firstName: 'Maya',
    lastName: 'Rivera',
    email: 'maya@example.com',
    phone: '+1 555-0101',
    role: 'Signed Model',
    status: 'current',
    workArea: 'Modeling',
    division: 'Modeling',
    niches: ['Commercial', 'Editorial'],
    property: 'Nzinga Management Agency',
    bankReady: true,
    taxFormsReady: true,
    available: false,
    bookedDates: ['2026-08-12', '2026-08-13'],
    contractStart: '2025-09-01',
    contractEnd: null,
    linkedProspectId: 'pros_maya',
    profilePhoto: seedProfilePhoto('Maya Rivera', 'MR', '#7c3aed'),
    portalAssets: [
      {
        name: 'Nike_Commercial_Lookbook.svg',
        data: seedProfilePhoto('Maya Rivera', 'MR', '#0f766e').data,
        type: 'image/svg+xml',
        doc_type: 'lookbook',
        uploaded_at: '2026-08-10T12:00:00Z',
        uploaded_by: 'Sarah Chen',
        status: 'verified',
      },
      {
        ...makeTextContractDocument(
          'Nike_Aug_Call_Sheet.txt',
          'NIKE COMMERCIAL — CALL SHEET\n\nTalent: Maya Rivera\nDates: 12–13 Aug 2026\nCall time: 7:00 AM\nLocation: Northlight Studios, Atlanta\nAgent: Sarah Chen\n',
        ),
        doc_type: 'call_sheet',
        uploaded_at: '2026-08-11T09:00:00Z',
        uploaded_by: 'Sarah Chen',
        status: 'received',
      },
    ],
    udf: {
      stageName: 'Maya Rivera',
      talentTypes: ['Modeling'],
      talentStatus: 'Current',
      representationType: 'exclusive',
      assignedAgent: 'Sarah Chen',
      height: "5'9\"",
      weight: '125 lbs',
      clothingSize: '4',
      shoeSize: '9',
      hairColor: 'Dark brown',
      eyeColor: 'Brown',
      bust: '34',
      waist: '25',
      hips: '36',
      modelingCategory: 'Commercial, Editorial',
      preferredContact: 'Email',
      primaryPlatform: 'Instagram',
      socialHandles: '@mayarivera',
      totalFollowers: '48,000',
      engagementRate: '3.2%',
      contentCategory: 'Fashion, lifestyle',
      usageRights: 'Nike commercial stills: North America, 1 year from first use. Video: worldwide, 6 months.',
    },
  },
  {
    id: 'talent_leo',
    accountId: 'NZG-200102',
    name: 'Leo Park',
    firstName: 'Leo',
    lastName: 'Park',
    email: 'leo@example.com',
    phone: '+1 555-0102',
    role: 'Signed Model',
    status: 'current',
    workArea: 'Modeling',
    division: 'Modeling',
    niches: ['Lifestyle', 'Fitness'],
    property: 'Nzinga Management Agency',
    bankReady: true,
    taxFormsReady: true,
    available: true,
    bookedDates: [],
    contractStart: '2026-01-01',
    contractEnd: null,
  },
  {
    id: 'talent_ava',
    accountId: 'NZG-200103',
    name: 'Ava Brooks',
    firstName: 'Ava',
    lastName: 'Brooks',
    email: 'ava@example.com',
    phone: '+1 555-0103',
    role: 'Signed Model',
    status: 'future',
    workArea: 'Modeling',
    division: 'Modeling',
    niches: ['Beauty', 'Runway'],
    property: 'Nzinga Management Agency',
    bankReady: false,
    taxFormsReady: true,
    available: true,
    bookedDates: [],
    contractStart: '2026-09-01',
    contractEnd: null,
  },
]

export const AGENCY_PROSPECTS_SEED: AgencyProspect[] = [
  {
    id: 'pros_1',
    accountId: 'NZG-200001',
    name: 'Kai Johnson',
    email: 'kai@example.com',
    workArea: 'Acting',
    firstName: 'Kai',
    lastName: 'Johnson',
    phone: '+1 555-0201',
    stage: 'screening_completed',
    source: 'Portal application',
    submittedAt: '2026-08-01T10:00:00Z',
    notes: 'Awaiting agent screening.',
    organization: 'NZG',
    property: 'Nzinga Management Agency',
    street: '120 Market St',
    city: 'Atlanta',
    state: 'GA',
    postal: '30303',
    messageEmails: ['kai@example.com'],
    assignedAgentName: 'Sarah Chen',
    representationType: 'exclusive',
    termLengthYears: 1,
    lastLoginAt: '2026-08-12T14:22:00Z',
    contractStart: '2026-01-15',
    contractEnd: null,
    linkedApplicationId: 'app_kai',
    udf: {
      stageName: 'Kai Johnson',
      talentTypes: ['Acting'],
      talentStatus: 'Prospect',
      representationType: 'exclusive',
      assignedAgent: 'Sarah Chen',
      actingCategory: 'Commercial',
    },
    contracts: [
      seededContract({
        id: 'ctr_kai_past',
        title: 'Representation Agreement 2025',
        status: 'past',
        startDate: '2025-01-15',
        endDate: '2026-01-14',
        representationType: 'exclusive',
        termLengthYears: 1,
        talentName: 'Kai Johnson',
      }),
      seededContract({
        id: 'ctr_kai_current',
        title: 'Representation Agreement 2026',
        status: 'current',
        startDate: '2026-01-15',
        endDate: null,
        representationType: 'exclusive',
        termLengthYears: 1,
        talentName: 'Kai Johnson',
      }),
    ],
  },
  {
    id: 'pros_2',
    accountId: 'NZG-200002',
    name: 'Riley Quinn',
    firstName: 'Riley',
    lastName: 'Quinn',
    email: 'riley@example.com',
    phone: '+1 555-0202',
    workArea: 'Modeling',
    stage: 'communicating',
    source: 'Scout referral',
    submittedAt: '2026-07-28T14:00:00Z',
    notes: 'Interview scheduled next week.',
    organization: 'NZG',
    property: 'Nzinga Management Agency',
    street: '88 Peachtree Ave',
    city: 'Atlanta',
    state: 'GA',
    postal: '30308',
    messageEmails: ['riley@example.com'],
    assignedAgentName: 'Jordan Hayes',
    representationType: 'exclusive',
    termLengthYears: 1,
    lastLoginAt: '2026-08-10T09:05:00Z',
    contractStart: '2025-08-01',
    contractEnd: '2026-07-31',
    contracts: [
      seededContract({
        id: 'ctr_riley_past',
        title: 'Exclusive Modeling Agreement 2025–2026',
        status: 'past',
        startDate: '2025-08-01',
        endDate: '2026-07-31',
        representationType: 'exclusive',
        termLengthYears: 1,
        talentName: 'Riley Quinn',
      }),
    ],
  },
  {
    id: 'pros_3',
    accountId: 'NZG-200003',
    name: 'Sam Ortiz',
    firstName: 'Sam',
    lastName: 'Ortiz',
    email: 'sam@example.com',
    phone: '+1 555-0203',
    workArea: 'Acting',
    stage: 'new_prospect',
    source: 'Open call',
    submittedAt: '2026-08-04T09:00:00Z',
    notes: 'New inbound applicant.',
    organization: 'NZG',
    property: 'Nzinga Management Agency',
    street: '14 Decatur Rd',
    city: 'Decatur',
    state: 'GA',
    postal: '30030',
    messageEmails: ['sam@example.com'],
    assignedAgentName: 'Sarah Chen',
    representationType: 'nonexclusive',
    termLengthYears: 2,
    lastLoginAt: null,
    contractStart: null,
    contractEnd: null,
    contracts: [],
  },
  {
    id: 'pros_maya',
    accountId: 'NZG-200101',
    name: 'Maya Rivera',
    firstName: 'Maya',
    lastName: 'Rivera',
    email: 'maya@example.com',
    phone: '+1 555-0101',
    workArea: 'Modeling',
    stage: 'contract_completed',
    source: 'Signed client',
    submittedAt: '2025-08-20T10:00:00Z',
    notes: 'Demo client account for talent portal login.',
    organization: 'NZG',
    property: 'Nzinga Management Agency',
    street: '410 Peachtree St',
    city: 'Atlanta',
    state: 'GA',
    postal: '30308',
    messageEmails: ['maya@example.com'],
    assignedAgentName: 'Sarah Chen',
    representationType: 'exclusive',
    termLengthYears: 1,
    lastLoginAt: '2026-08-12T09:00:00Z',
    contractStart: '2025-09-01',
    contractEnd: null,
    profilePhoto: seedProfilePhoto('Maya Rivera', 'MR', '#7c3aed'),
    udf: {
      stageName: 'Maya Rivera',
      talentTypes: ['Modeling'],
      talentStatus: 'Current',
      representationType: 'exclusive',
      assignedAgent: 'Sarah Chen',
    },
    contracts: [
      seededContract({
        id: 'ctr_maya_current',
        title: 'Exclusive Modeling Agreement 2025',
        status: 'current',
        startDate: '2025-09-01',
        endDate: null,
        representationType: 'exclusive',
        termLengthYears: 1,
        talentName: 'Maya Rivera',
      }),
    ],
  },
]

export const SUPPORT_TICKETS_SEED: SupportTicket[] = [
  {
    id: 'tkt_1',
    subject: 'Confirm Maya availability — commercial shoot',
    clientId: 'client_nike',
    clientName: 'Nike',
    talentName: 'Maya Rivera',
    status: 'open',
    type: 'availability',
    priority: 'high',
    createdAt: '2026-08-05T08:15:00Z',
    dueDate: '2026-08-08',
    body: 'Nike production team needs confirmation that Maya is available for a $10,000 commercial shoot on Aug 12–13.',
    assignee: 'Sarah Chen',
  },
  {
    id: 'tkt_2',
    subject: 'Reschedule Nike briefing call',
    clientId: 'client_nike',
    clientName: 'Nike',
    talentName: 'Maya Rivera',
    status: 'in_progress',
    type: 'scheduling',
    priority: 'medium',
    createdAt: '2026-08-06T11:00:00Z',
    dueDate: '2026-08-07',
    body: 'Client asked to move the briefing from Aug 5 morning to later in the week.',
    assignee: 'Jordan Hayes',
  },
  {
    id: 'tkt_3',
    subject: 'Usage rights clarification on commercial agreement',
    clientId: 'client_nike',
    clientName: 'Nike',
    talentName: 'Maya Rivera',
    status: 'open',
    type: 'contract',
    priority: 'high',
    createdAt: '2026-08-06T15:30:00Z',
    dueDate: '2026-08-10',
    body: 'Legal wants confirmation on territory and duration for stills vs video usage.',
    assignee: 'Marcus Bell',
  },
]

export const AGENCY_TASKS_SEED: AgencyTask[] = [
  {
    id: 'task_1',
    title: 'Send contract agreement to Nike production team',
    assignee: 'Sarah Chen',
    due: '2026-08-06',
    status: 'open',
    relatedClient: 'Nike',
  },
]

export const CHECKLIST_SEED: ChecklistItem[] = [
  { id: 'chk_1', title: 'Review Nike support ticket — confirm Maya availability', done: false },
  { id: 'chk_2', title: 'Check Appointments for Nike briefing call', done: false },
  { id: 'chk_3', title: 'Create Agency Task: send contract to Nike', done: false },
  { id: 'chk_4', title: 'Block Maya on Shared Calendar for shoot dates', done: false },
]

export const APPOINTMENTS_SEED: Appointment[] = [
  {
    id: 'appt_1',
    title: 'Nike initial briefing call',
    withWhom: 'Nike',
    clientNames: ['Nike'],
    agentNames: ['Sarah Chen'],
    talentNames: ['Maya Rivera'],
    startsAt: '2026-08-05T10:00:00Z',
    endsAt: '2026-08-05T10:30:00Z',
    location: 'Zoom',
    notes: 'Discuss Maya commercial shoot scope and usage.',
  },
]

export const CALENDAR_EVENTS_SEED: CalendarEvent[] = [
  {
    id: 'cal_1',
    title: 'Nike briefing call',
    date: '2026-08-05',
    talentName: 'Maya Rivera',
    clientName: 'Nike',
    type: 'meeting',
  },
  {
    id: 'cal_2',
    title: 'Maya — Nike Commercial Shoot',
    date: '2026-08-12',
    talentName: 'Maya Rivera',
    clientName: 'Nike',
    type: 'booking',
    callTime: '07:00',
    talentCallResponse: 'pending',
  },
  {
    id: 'cal_3',
    title: 'Maya — Nike Commercial Shoot',
    date: '2026-08-13',
    talentName: 'Maya Rivera',
    clientName: 'Nike',
    type: 'booking',
    callTime: '07:00',
    talentCallResponse: 'pending',
  },
]

export const INVOICES_SEED: ClientInvoice[] = [
  {
    id: 'inv_nike_1',
    clientId: 'client_nike',
    clientName: 'Nike',
    talentName: 'Maya Rivera',
    project: '$10,000 Commercial Shoot',
    amount: 10000,
    commissionPct: 20,
    status: 'sent',
    issuedAt: '2026-08-14',
    dueAt: '2026-09-13',
    interestApplied: 0,
    taxId: '13-1234567',
    taxRatePct: 8.875,
    taxAmount: 888,
    invoiceNumber: 'INV-2026-001',
    poNumber: 'PO-NIKE-8842',
    paymentTerms: 'Net 30',
    billingAddress: 'One Bowerman Dr, Beaverton, OR 97005',
    notes: 'Commercial shoot package — tax applied at NY combined rate.',
    document: null,
  },
  {
    id: 'inv_nike_2',
    clientId: 'client_nike',
    clientName: 'Nike',
    talentName: 'Leo Park',
    project: 'Lifestyle Lookbook Day Rate',
    amount: 4500,
    commissionPct: 20,
    status: 'sent',
    issuedAt: '2026-08-10',
    dueAt: '2026-09-09',
    interestApplied: 0,
    taxId: '13-1234567',
    taxRatePct: 8.875,
    taxAmount: 399,
    invoiceNumber: 'INV-2026-002',
    poNumber: 'PO-NIKE-8843',
    paymentTerms: 'Net 30',
    billingAddress: 'One Bowerman Dr, Beaverton, OR 97005',
    notes: '',
    document: null,
  },
  {
    id: 'inv_nike_3',
    clientId: 'client_nike',
    clientName: 'Nike',
    talentName: 'Ava Brooks',
    project: 'Beauty Campaign Still Set',
    amount: 6200,
    commissionPct: 20,
    status: 'sent',
    issuedAt: '2026-08-11',
    dueAt: '2026-09-10',
    interestApplied: 0,
    taxId: '13-1234567',
    taxRatePct: 8.875,
    taxAmount: 550,
    invoiceNumber: 'INV-2026-003',
    poNumber: '',
    paymentTerms: 'Net 30',
    billingAddress: 'One Bowerman Dr, Beaverton, OR 97005',
    notes: '',
    document: null,
  },
  {
    id: 'inv_nike_4',
    clientId: 'client_nike',
    clientName: 'Nike',
    talentName: 'Maya Rivera',
    project: 'Usage Buyout — Social Cutdowns',
    amount: 2800,
    commissionPct: 20,
    status: 'sent',
    issuedAt: '2026-08-12',
    dueAt: '2026-09-11',
    interestApplied: 0,
    taxId: '13-1234567',
    taxRatePct: 0,
    taxAmount: 0,
    invoiceNumber: 'INV-2026-004',
    poNumber: 'PO-NIKE-8901',
    paymentTerms: 'Due on receipt',
    billingAddress: 'One Bowerman Dr, Beaverton, OR 97005',
    notes: 'Tax-exempt usage buyout.',
    document: null,
  },
  {
    id: 'inv_maya_paid',
    clientId: 'client_nike',
    clientName: 'Nike',
    talentName: 'Maya Rivera',
    project: 'Spring Lookbook Day Rate',
    amount: 3500,
    commissionPct: 20,
    status: 'paid',
    issuedAt: '2026-06-02',
    dueAt: '2026-07-02',
    paidAt: '2026-06-28',
    interestApplied: 0,
    taxId: '13-1234567',
    taxRatePct: 0,
    taxAmount: 0,
    invoiceNumber: 'INV-2026-000',
    poNumber: 'PO-NIKE-8010',
    paymentTerms: 'Net 30',
    billingAddress: 'One Bowerman Dr, Beaverton, OR 97005',
    notes: 'Paid day rate — demo payment history.',
    document: null,
  },
]

export const RETAINER_PLANS_SEED: RetainerPlan[] = []

export const ESCROW_SEED: EscrowDeposit[] = [
  {
    id: 'esc_maya_1',
    clientName: 'Nike',
    talentName: 'Maya Rivera',
    project: '$10,000 Commercial Shoot',
    amount: 8000,
    receivedAt: '2026-08-14',
    status: 'pending',
    invoiceId: 'inv_nike_1',
    notes: 'Talent share held in trust pending shoot wrap and usage delivery.',
  },
]

export const EXPENSE_LOGS_SEED: ExpensePayoutLog[] = [
  {
    id: 'exp_maya_1',
    project: '$10,000 Commercial Shoot',
    clientName: 'Nike',
    talentName: 'Maya Rivera',
    gross: 10000,
    agencyCommission: 2000,
    talentShare: 8000,
    status: 'pending',
    loggedAt: '2026-08-14',
  },
  {
    id: 'exp_maya_2',
    project: 'Spring Lookbook Day Rate',
    clientName: 'Nike',
    talentName: 'Maya Rivera',
    gross: 3500,
    agencyCommission: 700,
    talentShare: 2800,
    status: 'completed',
    loggedAt: '2026-06-28',
  },
]

export const VENDORS_SEED: Vendor[] = [
  {
    id: 'ven_maya',
    name: 'Maya Rivera',
    type: 'talent',
    bankLast4: '4821',
    taxFormsReady: true,
    email: 'maya@example.com',
  },
  {
    id: 'ven_studio',
    name: 'Northlight Studios',
    type: 'service',
    bankLast4: '1190',
    taxFormsReady: true,
    email: 'billing@northlight.example',
  },
]

export const DISBURSEMENTS_SEED: Disbursement[] = [
  {
    id: 'dis_maya_1',
    payee: 'Maya Rivera',
    amount: 2800,
    method: 'ACH',
    status: 'completed',
    paidAt: '2026-06-28',
    project: 'Spring Lookbook Day Rate',
  },
]

export const MESSAGES_SEED: MessageThread[] = [
  {
    id: 'msg_1',
    channel: 'email',
    to: 'production@nike.example',
    subject: 'Maya availability confirmation',
    preview: 'Confirming Maya Rivera for Aug 12–13 commercial…',
    sentAt: '2026-08-05T09:00:00Z',
    status: 'sent',
  },
]

export const PROJECT_SCENARIO = {
  name: '$10,000 Commercial Shoot',
  client: 'Nike',
  talent: 'Maya Rivera',
  gross: 10000,
  commissionPct: 20,
  agencyShare: 2000,
  talentShare: 8000,
}
