import type { ApplicationsMap, HistoryEntry, Talent, Task, User } from '@/types'

export const USERS: User[] = [
  {
    id: 'u1',
    name: 'Jordan Hayes',
    initials: 'JH',
    role: 'scout',
    email: 'jordan@nzinga.co',
    password: 'scout123',
    title: 'Talent Scout',
    color: '#7c3aed',
  },
  {
    id: 'u2',
    name: 'Marcus Bell',
    initials: 'MB',
    role: 'team1_lead',
    email: 'marcus@nzinga.co',
    password: 'lead123',
    title: 'Team 1 Lead',
    color: '#f59e0b',
  },
  {
    id: 'u3',
    name: 'Priya Okafor',
    initials: 'PO',
    role: 'ops_specialist',
    email: 'priya@nzinga.co',
    password: 'ops123',
    title: 'Ops Specialist',
    color: '#3b82f6',
  },
  {
    id: 'u4',
    name: 'Devon Cruz',
    initials: 'DC',
    role: 'team2_lead',
    email: 'devon@nzinga.co',
    password: 'lead2123',
    title: 'Team 2 Lead',
    color: '#06b6d4',
  },
  {
    id: 'u5',
    name: 'Simone Nzinga',
    initials: 'SN',
    role: 'director',
    email: 'simone@nzinga.co',
    password: 'director123',
    title: 'Executive Director',
    color: '#10b981',
  },
  {
    id: 'u6',
    name: 'Alexis Grant',
    initials: 'AG',
    role: 'success_manager',
    email: 'alexis@nzinga.co',
    password: 'success123',
    title: 'Success Manager',
    color: '#ec4899',
  },
]

export const TASKS_SEED: Task[] = [
  {
    id: 'tk1',
    title: 'Follow up with Zara re: Q3 merch collab',
    assigned_to: 'u6',
    related_talent: 't1',
    due: '2026-05-25',
    priority: 'high',
    status: 'open',
    created_by: 'u5',
    created_at: '2026-05-19T09:00:00Z',
    notes: 'Discuss Q3 launch timeline.',
  },
  {
    id: 'tk2',
    title: 'Collect W-9 from Mia Torres',
    assigned_to: 'u3',
    related_talent: 't3',
    due: '2026-05-21',
    priority: 'urgent',
    status: 'open',
    created_by: 'u3',
    created_at: '2026-05-19T10:00:00Z',
    notes: 'Tax doc still outstanding.',
  },
  {
    id: 'tk3',
    title: 'Review Darius Cole scoring rationale',
    assigned_to: 'u2',
    related_talent: 't2',
    due: '2026-05-22',
    priority: 'medium',
    status: 'open',
    created_by: 'u2',
    created_at: '2026-05-18T14:00:00Z',
    notes: 'Check pillar 2 alignment.',
  },
]

export const HISTORY_SEED: HistoryEntry[] = [
  {
    id: 'h1',
    talent_id: 't1',
    user_id: 'u6',
    type: 'note',
    text: "Spoke with Zara. She's interested in the Q3 merch line.",
    ts: '2026-05-18T14:22:00Z',
    flagged: false,
    is_document: false,
  },
  {
    id: 'h2',
    talent_id: 't1',
    user_id: 'u5',
    type: 'call',
    text: 'Director check-in call. Onboarding confirmed complete.',
    ts: '2026-05-17T10:05:00Z',
    flagged: false,
    is_document: false,
  },
  {
    id: 'h3',
    talent_id: 't2',
    user_id: 'u2',
    type: 'note',
    text: 'Pillar 2 engagement score is borderline. Watching trend data.',
    ts: '2026-05-18T11:30:00Z',
    flagged: true,
    is_document: false,
  },
  {
    id: 'h4',
    talent_id: 't3',
    user_id: 'u3',
    type: 'document',
    text: 'W-9 uploaded for Mia Torres.',
    ts: '2026-05-18T09:15:00Z',
    flagged: false,
    is_document: true,
    doc_name: 'W-9_MiaTorres.pdf',
    doc_type: 'application/pdf',
  },
  {
    id: 'h5',
    talent_id: 't5',
    user_id: 'u4',
    type: 'note',
    text: 'All data verified. Approved for Director.',
    ts: '2026-05-15T10:00:00Z',
    flagged: false,
    is_document: false,
  },
]

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const talentsRaw = [
  {
    id: 't1',
    name: 'Zara Williams',
    stage: 'signed_onboarding',
    niches: ['Model', 'Influencer'],
    scout_id: 'u1',
    created_at: '2026-04-10T09:00:00Z',
    social_handle: '@zarawilliams',
    follower_count: '2.1M',
    er_pct: '8.2',
    platform: 'Instagram / TikTok',
    location: 'Atlanta, GA',
    pillar_scores: [4, 5, 4, 4, 5],
    pillar_rationales: [
      'Exceptional brand consistency.',
      'Viral ER above 8%.',
      'Zero controversy.',
      'Diverse content.',
      '3 active brand deals.',
    ],
    jordan_score: 4.4,
    revenue_path: 'Sponsored posts ($8k/mo). 90-day: $25k luxury fashion.',
    scout_summary: 'Top-tier digital creator with proven commercial appeal.',
    team1_notes: '',
    team1_decision: 'approved',
    compliance: {
      legal_name: true,
      gov_id: true,
      dob: true,
      address: true,
      email_phone: true,
      tax_doc: true,
      banking: true,
      social_ownership: true,
    },
    rep_type: 'Exclusive',
    commission: '15',
    term_length: '12 months',
    team2_notes: '',
    team2_decision: 'approved',
    director_decision: 'approved',
    portal_setup: true,
    technical_routing: true,
    warm_handoff: 'Keisha Morris – Influencer Division',
    warm_handoff_confirmed: true,
    revenue_ytd: '47200',
    revenue_projected: '180000',
    last_contacted: '2026-05-18',
    application_id: null,
    application_status: null,
    uploaded_docs: {},
    audit_log: [
      {
        user: 'Jordan Hayes',
        role: 'Scout',
        action: 'Created holding record',
        stage: 'holding_entry',
        ts: '2026-04-10T09:00:00Z',
      },
      {
        user: 'Jordan Hayes',
        role: 'Scout',
        action: 'Completed Talent Packet → Scout Complete',
        stage: 'scout_complete',
        ts: '2026-04-11T14:22:00Z',
      },
      {
        user: 'Marcus Bell',
        role: 'Team 1 Lead',
        action: 'Approved for Ops',
        stage: 'team1_review',
        ts: '2026-04-12T10:05:00Z',
      },
      {
        user: 'Priya Okafor',
        role: 'Ops Specialist',
        action: 'Compliance verified → Team 2 Audit',
        stage: 'ops_processing',
        ts: '2026-04-13T16:40:00Z',
      },
      {
        user: 'Devon Cruz',
        role: 'Team 2 Lead',
        action: 'Approved for Director',
        stage: 'team2_audit',
        ts: '2026-04-14T11:20:00Z',
      },
      {
        user: 'Simone Nzinga',
        role: 'Director',
        action: 'Approved – Sign Client',
        stage: 'executive_review',
        ts: '2026-04-15T09:55:00Z',
      },
      {
        user: 'Alexis Grant',
        role: 'Success Manager',
        action: 'Warm hand-off confirmed',
        stage: 'signed_onboarding',
        ts: '2026-04-16T13:30:00Z',
      },
    ],
  },
  {
    id: 't2',
    name: 'Darius Cole',
    stage: 'team1_review',
    niches: ['Actor', 'Model'],
    scout_id: 'u1',
    created_at: '2026-05-01T11:00:00Z',
    social_handle: '@dariuscole',
    follower_count: '890K',
    er_pct: '3.1',
    platform: 'Instagram / YouTube',
    location: 'Los Angeles, CA',
    pillar_scores: [4, 3, 4, 4, 4],
    pillar_rationales: [
      'SAG eligible.',
      'ER slightly low.',
      'Clean image.',
      'Indie drama niche.',
      'Two commercials.',
    ],
    jordan_score: 3.8,
    revenue_path: 'Commercials $3k/mo. 90-day: 2 bookings.',
    scout_summary: 'Disciplined actor, pillar 2 borderline.',
    team1_notes: '',
    team1_decision: null,
    compliance: {},
    rep_type: '',
    commission: '',
    term_length: '',
    team2_notes: '',
    team2_decision: null,
    director_decision: null,
    portal_setup: false,
    technical_routing: false,
    warm_handoff: '',
    warm_handoff_confirmed: false,
    revenue_ytd: '0',
    revenue_projected: '36000',
    last_contacted: '2026-05-02',
    application_id: null,
    application_status: null,
    uploaded_docs: {},
    audit_log: [
      {
        user: 'Jordan Hayes',
        role: 'Scout',
        action: 'Created holding record',
        stage: 'holding_entry',
        ts: '2026-05-01T11:00:00Z',
      },
      {
        user: 'Jordan Hayes',
        role: 'Scout',
        action: 'Completed Talent Packet → Scout Complete',
        stage: 'scout_complete',
        ts: '2026-05-02T15:10:00Z',
      },
    ],
  },
  {
    id: 't3',
    name: 'Mia Torres',
    stage: 'ops_processing',
    niches: ['Athlete', 'Influencer'],
    scout_id: 'u1',
    created_at: '2026-04-20T08:30:00Z',
    social_handle: '@miatorres_fit',
    follower_count: '1.4M',
    er_pct: '6.8',
    platform: 'Instagram / YouTube',
    location: 'Houston, TX',
    pillar_scores: [5, 4, 4, 4, 4],
    pillar_rationales: [
      'D1 athlete 3 titles.',
      'High engagement.',
      'Zero risk.',
      'Consistent posting.',
      'NIL $12k YTD.',
    ],
    jordan_score: 4.2,
    revenue_path: 'NIL deals. 90-day: Adidas NIL activation.',
    scout_summary: 'Elite D1 athlete with exceptional NIL positioning.',
    team1_notes: '',
    team1_decision: 'approved',
    compliance: {
      legal_name: true,
      gov_id: true,
      dob: true,
      address: true,
      email_phone: true,
      tax_doc: false,
      banking: false,
      social_ownership: true,
    },
    rep_type: 'Exclusive',
    commission: '20',
    term_length: '24 months',
    team2_notes: '',
    team2_decision: null,
    director_decision: null,
    portal_setup: false,
    technical_routing: false,
    warm_handoff: '',
    warm_handoff_confirmed: false,
    revenue_ytd: '12000',
    revenue_projected: '95000',
    last_contacted: '2026-05-18',
    application_id: null,
    application_status: null,
    uploaded_docs: {},
    audit_log: [
      {
        user: 'Jordan Hayes',
        role: 'Scout',
        action: 'Created holding record',
        stage: 'holding_entry',
        ts: '2026-04-20T08:30:00Z',
      },
      {
        user: 'Marcus Bell',
        role: 'Team 1 Lead',
        action: 'Approved for Ops',
        stage: 'team1_review',
        ts: '2026-04-22T14:00:00Z',
      },
    ],
  },
  {
    id: 't4',
    name: 'Kai Johnson',
    stage: 'holding_entry',
    niches: [],
    scout_id: 'u1',
    created_at: '2026-05-18T10:00:00Z',
    social_handle: '@kaij_music',
    follower_count: '320K',
    er_pct: '2.1',
    platform: 'TikTok / Instagram',
    location: 'Chicago, IL',
    pillar_scores: [0, 0, 0, 0, 0],
    pillar_rationales: ['', '', '', '', ''],
    jordan_score: 0,
    revenue_path: '',
    scout_summary: '',
    team1_notes: '',
    team1_decision: null,
    compliance: {},
    rep_type: '',
    commission: '',
    term_length: '',
    team2_notes: '',
    team2_decision: null,
    director_decision: null,
    portal_setup: false,
    technical_routing: false,
    warm_handoff: '',
    warm_handoff_confirmed: false,
    revenue_ytd: '0',
    revenue_projected: '0',
    last_contacted: '2026-05-18',
    application_id: 'app_kai',
    application_status: 'in_progress',
    uploaded_docs: {},
    audit_log: [
      {
        user: 'Jordan Hayes',
        role: 'Scout',
        action: 'Created holding record',
        stage: 'holding_entry',
        ts: '2026-05-18T10:00:00Z',
      },
    ],
  },
  {
    id: 't5',
    name: 'Renee Park',
    stage: 'executive_review',
    niches: ['Actor', 'Influencer'],
    scout_id: 'u1',
    created_at: '2026-04-05T07:20:00Z',
    social_handle: '@reneepark',
    follower_count: '3.8M',
    er_pct: '12.0',
    platform: 'Instagram / YouTube / TikTok',
    location: 'New York, NY',
    pillar_scores: [5, 5, 5, 4, 5],
    pillar_rationales: [
      'Series regular.',
      'ER 12%.',
      'Spotless record.',
      'Cross-platform.',
      '$40k/mo brand.',
    ],
    jordan_score: 4.8,
    revenue_path: 'Series fees + brand integrations. 90-day: $150k.',
    scout_summary: 'Strongest pipeline candidate this quarter.',
    team1_notes: '',
    team1_decision: 'approved',
    compliance: {
      legal_name: true,
      gov_id: true,
      dob: true,
      address: true,
      email_phone: true,
      tax_doc: true,
      banking: true,
      social_ownership: true,
    },
    rep_type: 'Exclusive',
    commission: '15',
    term_length: '18 months',
    team2_notes: '',
    team2_decision: 'approved',
    director_decision: null,
    portal_setup: false,
    technical_routing: false,
    warm_handoff: '',
    warm_handoff_confirmed: false,
    revenue_ytd: '120000',
    revenue_projected: '480000',
    last_contacted: '2026-05-15',
    application_id: null,
    application_status: null,
    uploaded_docs: {},
    audit_log: [
      {
        user: 'Jordan Hayes',
        role: 'Scout',
        action: 'Created holding record',
        stage: 'holding_entry',
        ts: '2026-04-05T07:20:00Z',
      },
      {
        user: 'Devon Cruz',
        role: 'Team 2 Lead',
        action: 'Approved for Director',
        stage: 'team2_audit',
        ts: '2026-04-09T10:00:00Z',
      },
    ],
  },
] as Talent[]

export const TALENTS_SEED: Talent[] = talentsRaw

export const APPLICATIONS_SEED: ApplicationsMap = {
  app_kai: {
    id: 'app_kai',
    talent_id: 't4',
    access_code: 'KAI2026',
    talent_name: 'Kai Johnson',
    talent_email: 'kai@example.com',
    status: 'in_progress',
    created_at: '2026-05-18T10:00:00Z',
    last_saved: '2026-05-19T14:30:00Z',
    completed_sections: ['personal', 'social'],
    data: {
      legal_first: 'Kai',
      legal_last: 'Johnson',
      dob: '2000-03-15',
      phone: '312-555-0199',
      email: 'kai@example.com',
      address: '123 West Loop Dr',
      city: 'Chicago',
      state: 'IL',
      zip: '60601',
      primary_handle: '@kaij_music',
      primary_platform: 'TikTok',
      follower_count: '320K',
    },
  },
}
