import type { ApplicationsMap, HistoryEntry, Talent, Task, User } from '@/types'
import { ACCOUNT_NUMBER_START, formatAccountNumber } from '@/lib/account-number'

export const USERS: User[] = [
  {
    id: 'u1',
    name: 'Jordan Hayes',
    initials: 'JH',
    role: 'scout',
    email: 'jordan@nzinga.co',
    password: 'scout123',
    title: 'Talent Scout',
    color: '#7c3aed',
    company_code: 'NZG',
  },
  {
    id: 'u2',
    name: 'Marcus Bell',
    initials: 'MB',
    role: 'team1_lead',
    email: 'marcus@nzinga.co',
    password: 'lead123',
    title: 'Team 1 Lead',
    color: '#f59e0b',
    company_code: 'NZG',
  },
  {
    id: 'u3',
    name: 'Priya Okafor',
    initials: 'PO',
    role: 'ops_specialist',
    email: 'priya@nzinga.co',
    password: 'ops123',
    title: 'Ops Specialist',
    color: '#3b82f6',
    company_code: 'NZG',
  },
  {
    id: 'u4',
    name: 'Devon Cruz',
    initials: 'DC',
    role: 'team2_lead',
    email: 'devon@nzinga.co',
    password: 'lead2123',
    title: 'Team 2 Lead',
    color: '#06b6d4',
    company_code: 'NZG',
  },
  {
    id: 'u5',
    name: 'Simone Nzinga',
    initials: 'SN',
    role: 'director',
    email: 'simone@nzinga.co',
    password: 'director123',
    title: 'Executive Director',
    color: '#10b981',
    company_code: 'NZG',
  },
  {
    id: 'u6',
    name: 'Alexis Grant',
    initials: 'AG',
    role: 'success_manager',
    email: 'alexis@nzinga.co',
    password: 'success123',
    title: 'Success Manager',
    color: '#ec4899',
    company_code: 'NZG',
  },
]

export const TASKS_SEED: Task[] = [
  {
    id: 'tk1',
    title: 'Follow up with Zara re: Q3 merch collab',
    assigned_to: 'u6',
    related_talent: 't1',
    due: '2026-05-25',
    priority: 'high',
    status: 'open',
    created_by: 'u5',
    created_at: '2026-05-19T09:00:00Z',
    notes: 'Discuss Q3 launch timeline.',
  },
  {
    id: 'tk2',
    title: 'Collect W-9 from Mia Torres',
    assigned_to: 'u3',
    related_talent: 't3',
    due: '2026-05-21',
    priority: 'urgent',
    status: 'open',
    created_by: 'u3',
    created_at: '2026-05-19T10:00:00Z',
    notes: 'Tax doc still outstanding.',
  },
  {
    id: 'tk3',
    title: 'Review Darius Cole scoring rationale',
    assigned_to: 'u2',
    related_talent: 't2',
    due: '2026-05-22',
    priority: 'medium',
    status: 'open',
    created_by: 'u2',
    created_at: '2026-05-18T14:00:00Z',
    notes: 'Check pillar 2 alignment.',
  },
]

export const HISTORY_SEED: HistoryEntry[] = [
  {
    id: 'h1',
    talent_id: 't1',
    user_id: 'u6',
    type: 'note',
    text: "Spoke with Zara. She's interested in the Q3 merch line.",
    ts: '2026-05-18T14:22:00Z',
    flagged: false,
    is_document: false,
  },
  {
    id: 'h2',
    talent_id: 't1',
    user_id: 'u5',
    type: 'call',
    text: 'Director check-in call. Onboarding confirmed complete.',
    ts: '2026-05-17T10:05:00Z',
    flagged: false,
    is_document: false,
  },
  {
    id: 'h3',
    talent_id: 't2',
    user_id: 'u2',
    type: 'note',
    text: 'Pillar 2 engagement score is borderline. Watching trend data.',
    ts: '2026-05-18T11:30:00Z',
    flagged: true,
    is_document: false,
  },
  {
    id: 'h4',
    talent_id: 't3',
    user_id: 'u3',
    type: 'document',
    text: 'W-9 uploaded for Mia Torres.',
    ts: '2026-05-18T09:15:00Z',
    flagged: false,
    is_document: true,
    doc_name: 'W-9_MiaTorres.pdf',
    doc_type: 'application/pdf',
  },
  {
    id: 'h5',
    talent_id: 't5',
    user_id: 'u4',
    type: 'note',
    text: 'All data verified. Approved for Director.',
    ts: '2026-05-15T10:00:00Z',
    flagged: false,
    is_document: false,
  },
]

const talentsRaw = [
  {
    id: 't1',
    name: 'Zara Williams',
    stage: 'signed_onboarding',
    niches: ['Model', 'Influencer'],
    scout_id: 'u1',
    created_at: '2026-04-10T09:00:00Z',
    social_handle: '@zarawilliams',
    follower_count: '2.1M',
    er_pct: '8.2',
    platform: 'Instagram / TikTok',
    location: 'Atlanta, GA',
    pillar_scores: [4, 5, 4, 4, 5],
    pillar_rationales: [
      'Exceptional brand consistency.',
      'Viral ER above 8%.',
      'Zero controversy.',
      'Diverse content.',
      '3 active brand deals.',
    ],
    jordan_score: 4.4,
    revenue_path: 'Sponsored posts ($8k/mo). 90-day: $25k luxury fashion.',
    scout_summary: 'Top-tier digital creator with proven commercial appeal.',
    team1_notes: '',
    team1_decision: 'approved',
    compliance: {
      legal_name: true,
      gov_id: true,
      dob: true,
      address: true,
      email_phone: true,
      tax_doc: true,
      banking: true,
      social_ownership: true,
    },
    rep_type: 'Exclusive',
    commission: '15',
    term_length: '12 months',
    team2_notes: '',
    team2_decision: 'approved',
    director_decision: 'approved',
    portal_setup: true,
    technical_routing: true,
    warm_handoff: 'Keisha Morris – Influencer Division',
    warm_handoff_confirmed: true,
    revenue_ytd: '47200',
    revenue_projected: '180000',
    last_contacted: '2026-05-18',
    application_id: null,
    application_status: null,
    uploaded_docs: {},
    audit_log: [
      {
        user: 'Jordan Hayes',
        role: 'Scout',
        action: 'Created holding record',
        stage: 'holding_entry',
        ts: '2026-04-10T09:00:00Z',
      },
      {
        user: 'Jordan Hayes',
        role: 'Scout',
        action: 'Completed Talent Packet → Scout Complete',
        stage: 'scout_complete',
        ts: '2026-04-11T14:22:00Z',
      },
      {
        user: 'Marcus Bell',
        role: 'Team 1 Lead',
        action: 'Approved for Ops',
        stage: 'team1_review',
        ts: '2026-04-12T10:05:00Z',
      },
      {
        user: 'Priya Okafor',
        role: 'Ops Specialist',
        action: 'Compliance verified → Team 2 Audit',
        stage: 'ops_processing',
        ts: '2026-04-13T16:40:00Z',
      },
      {
        user: 'Devon Cruz',
        role: 'Team 2 Lead',
        action: 'Approved for Director',
        stage: 'team2_audit',
        ts: '2026-04-14T11:20:00Z',
      },
      {
        user: 'Simone Nzinga',
        role: 'Director',
        action: 'Approved – Sign Client',
        stage: 'executive_review',
        ts: '2026-04-15T09:55:00Z',
      },
      {
        user: 'Alexis Grant',
        role: 'Success Manager',
        action: 'Warm hand-off confirmed',
        stage: 'signed_onboarding',
        ts: '2026-04-16T13:30:00Z',
      },
    ],
  },
  {
    id: 't2',
    name: 'Darius Cole',
    stage: 'team1_review',
    niches: ['Actor', 'Model'],
    scout_id: 'u1',
    created_at: '2026-05-01T11:00:00Z',
    social_handle: '@dariuscole',
    follower_count: '890K',
    er_pct: '3.1',
    platform: 'Instagram / YouTube',
    location: 'Los Angeles, CA',
    pillar_scores: [4, 3, 4, 4, 4],
    pillar_rationales: [
      'SAG eligible.',
      'ER slightly low.',
      'Clean image.',
      'Indie drama niche.',
      'Two commercials.',
    ],
    jordan_score: 3.8,
    revenue_path: 'Commercials $3k/mo. 90-day: 2 bookings.',
    scout_summary: 'Disciplined actor, pillar 2 borderline.',
    team1_notes: '',
    team1_decision: null,
    compliance: {},
    rep_type: '',
    commission: '',
    term_length: '',
    team2_notes: '',
    team2_decision: null,
    director_decision: null,
    portal_setup: false,
    technical_routing: false,
    warm_handoff: '',
    warm_handoff_confirmed: false,
    revenue_ytd: '0',
    revenue_projected: '36000',
    last_contacted: '2026-05-02',
    application_id: null,
    application_status: null,
    uploaded_docs: {},
    audit_log: [
      {
        user: 'Jordan Hayes',
        role: 'Scout',
        action: 'Created holding record',
        stage: 'holding_entry',
        ts: '2026-05-01T11:00:00Z',
      },
      {
        user: 'Jordan Hayes',
        role: 'Scout',
        action: 'Completed Talent Packet → Scout Complete',
        stage: 'scout_complete',
        ts: '2026-05-02T15:10:00Z',
      },
    ],
  },
  {
    id: 't3',
    name: 'Mia Torres',
    stage: 'ops_processing',
    niches: ['Athlete', 'Influencer'],
    scout_id: 'u1',
    created_at: '2026-04-20T08:30:00Z',
    social_handle: '@miatorres_fit',
    follower_count: '1.4M',
    er_pct: '6.8',
    platform: 'Instagram / YouTube',
    location: 'Houston, TX',
    pillar_scores: [5, 4, 4, 4, 4],
    pillar_rationales: [
      'D1 athlete 3 titles.',
      'High engagement.',
      'Zero risk.',
      'Consistent posting.',
      'NIL $12k YTD.',
    ],
    jordan_score: 4.2,
    revenue_path: 'NIL deals. 90-day: Adidas NIL activation.',
    scout_summary: 'Elite D1 athlete with exceptional NIL positioning.',
    team1_notes: '',
    team1_decision: 'approved',
    compliance: {
      legal_name: true,
      gov_id: true,
      dob: true,
      address: true,
      email_phone: true,
      tax_doc: false,
      banking: false,
      social_ownership: true,
    },
    rep_type: 'Exclusive',
    commission: '20',
    term_length: '24 months',
    team2_notes: '',
    team2_decision: null,
    director_decision: null,
    portal_setup: false,
    technical_routing: false,
    warm_handoff: '',
    warm_handoff_confirmed: false,
    revenue_ytd: '12000',
    revenue_projected: '95000',
    last_contacted: '2026-05-18',
    application_id: null,
    application_status: null,
    uploaded_docs: {},
    audit_log: [
      {
        user: 'Jordan Hayes',
        role: 'Scout',
        action: 'Created holding record',
        stage: 'holding_entry',
        ts: '2026-04-20T08:30:00Z',
      },
      {
        user: 'Marcus Bell',
        role: 'Team 1 Lead',
        action: 'Approved for Ops',
        stage: 'team1_review',
        ts: '2026-04-22T14:00:00Z',
      },
    ],
  },
  {
    id: 't4',
    name: 'Kai Johnson',
    stage: 'holding_entry',
    niches: [],
    scout_id: 'u1',
    created_at: '2026-05-18T10:00:00Z',
    social_handle: '@kaij_music',
    follower_count: '320K',
    er_pct: '2.1',
    platform: 'TikTok / Instagram',
    location: 'Chicago, IL',
    pillar_scores: [0, 0, 0, 0, 0],
    pillar_rationales: ['', '', '', '', ''],
    jordan_score: 0,
    revenue_path: '',
    scout_summary: '',
    team1_notes: '',
    team1_decision: null,
    compliance: {},
    rep_type: '',
    commission: '',
    term_length: '',
    team2_notes: '',
    team2_decision: null,
    director_decision: null,
    portal_setup: false,
    technical_routing: false,
    warm_handoff: '',
    warm_handoff_confirmed: false,
    revenue_ytd: '0',
    revenue_projected: '0',
    last_contacted: '2026-05-18',
    application_id: 'app_kai',
    application_status: 'in_progress',
    uploaded_docs: {},
    audit_log: [
      {
        user: 'Jordan Hayes',
        role: 'Scout',
        action: 'Created holding record',
        stage: 'holding_entry',
        ts: '2026-05-18T10:00:00Z',
      },
    ],
  },
  {
    id: 't5',
    name: 'Renee Park',
    stage: 'executive_review',
    niches: ['Actor', 'Influencer'],
    scout_id: 'u1',
    created_at: '2026-04-05T07:20:00Z',
    social_handle: '@reneepark',
    follower_count: '3.8M',
    er_pct: '12.0',
    platform: 'Instagram / YouTube / TikTok',
    location: 'New York, NY',
    pillar_scores: [5, 5, 5, 4, 5],
    pillar_rationales: [
      'Series regular.',
      'ER 12%.',
      'Spotless record.',
      'Cross-platform.',
      '$40k/mo brand.',
    ],
    jordan_score: 4.8,
    revenue_path: 'Series fees + brand integrations. 90-day: $150k.',
    scout_summary: 'Strongest pipeline candidate this quarter.',
    team1_notes: '',
    team1_decision: 'approved',
    compliance: {
      legal_name: true,
      gov_id: true,
      dob: true,
      address: true,
      email_phone: true,
      tax_doc: true,
      banking: true,
      social_ownership: true,
    },
    rep_type: 'Exclusive',
    commission: '15',
    term_length: '18 months',
    team2_notes: '',
    team2_decision: 'approved',
    director_decision: null,
    portal_setup: false,
    technical_routing: false,
    warm_handoff: '',
    warm_handoff_confirmed: false,
    revenue_ytd: '120000',
    revenue_projected: '480000',
    last_contacted: '2026-05-15',
    application_id: null,
    application_status: null,
    uploaded_docs: {},
    audit_log: [
      {
        user: 'Jordan Hayes',
        role: 'Scout',
        action: 'Created holding record',
        stage: 'holding_entry',
        ts: '2026-04-05T07:20:00Z',
      },
      {
        user: 'Devon Cruz',
        role: 'Team 2 Lead',
        action: 'Approved for Director',
        stage: 'team2_audit',
        ts: '2026-04-09T10:00:00Z',
      },
    ],
  },
  {
    id: 't6',
    name: 'Andre Simmons',
    stage: 'scout_complete',
    niches: ['Influencer', 'Model'],
    scout_id: 'u1',
    created_at: '2026-07-12T14:00:00Z',
    social_handle: '@andresimmons',
    follower_count: '640K',
    er_pct: '5.4',
    platform: 'TikTok / Instagram',
    location: 'Miami, FL',
    pillar_scores: [4, 4, 4, 3, 4],
    pillar_rationales: [
      'Strong lifestyle brand fit.',
      'Solid mid-funnel ER.',
      'No brand-safety flags.',
      'Fashion + travel mix.',
      'Two active affiliate deals.',
    ],
    jordan_score: 3.8,
    revenue_path: 'Affiliate + sponsored Reels. 90-day: beauty launch.',
    scout_summary: 'Ready for Team 1 — clean packet, consistent posting cadence.',
    team1_notes: '',
    team1_decision: null,
    compliance: {},
    rep_type: '',
    commission: '',
    term_length: '',
    team2_notes: '',
    team2_decision: null,
    director_decision: null,
    portal_setup: false,
    technical_routing: false,
    warm_handoff: '',
    warm_handoff_confirmed: false,
    revenue_ytd: '0',
    revenue_projected: '42000',
    last_contacted: '2026-07-28',
    application_id: null,
    application_status: null,
    uploaded_docs: {},
    audit_log: [
      {
        user: 'Jordan Hayes',
        role: 'Scout',
        action: 'Created holding record',
        stage: 'holding_entry',
        ts: '2026-07-12T14:00:00Z',
      },
      {
        user: 'Jordan Hayes',
        role: 'Scout',
        action: 'Completed Talent Packet → Scout Complete',
        stage: 'scout_complete',
        ts: '2026-07-20T11:15:00Z',
      },
    ],
  },
  {
    id: 't7',
    name: 'Kenji Nakamura',
    stage: 'team2_audit',
    niches: ['Actor', 'Influencer'],
    scout_id: 'u1',
    created_at: '2026-06-02T10:00:00Z',
    social_handle: '@kenjinakamura',
    follower_count: '1.1M',
    er_pct: '7.1',
    platform: 'YouTube / Instagram',
    location: 'Seattle, WA',
    pillar_scores: [5, 4, 5, 4, 4],
    pillar_rationales: [
      'Cross-over comedy/acting lane.',
      'High watch-time.',
      'Clean public record.',
      'Strong short-form + long-form.',
      'Prior network digital series.',
    ],
    jordan_score: 4.4,
    revenue_path: 'YouTube AdSense + brand integrations. 90-day: streaming pilot.',
    scout_summary: 'High-upside creator with entertainment crossover potential.',
    team1_notes: '',
    team1_decision: 'approved',
    compliance: {
      legal_name: true,
      gov_id: true,
      dob: true,
      address: true,
      email_phone: true,
      tax_doc: true,
      banking: true,
      social_ownership: true,
    },
    rep_type: 'Exclusive',
    commission: '15',
    term_length: '12 months',
    team2_notes: '',
    team2_decision: null,
    director_decision: null,
    portal_setup: false,
    technical_routing: false,
    warm_handoff: '',
    warm_handoff_confirmed: false,
    revenue_ytd: '38000',
    revenue_projected: '140000',
    last_contacted: '2026-07-30',
    application_id: null,
    application_status: null,
    uploaded_docs: {},
    audit_log: [
      {
        user: 'Priya Okafor',
        role: 'Ops Specialist',
        action: 'Compliance verified → Team 2 Audit',
        stage: 'ops_processing',
        ts: '2026-07-22T16:40:00Z',
      },
    ],
  },
  {
    id: 't8',
    name: 'Aaliyah Brooks',
    stage: 'holding_entry',
    niches: [],
    scout_id: 'u1',
    created_at: '2026-08-01T09:00:00Z',
    social_handle: '',
    follower_count: '',
    er_pct: '',
    platform: '',
    location: 'Atlanta, GA',
    pillar_scores: [0, 0, 0, 0, 0],
    pillar_rationales: ['', '', '', '', ''],
    jordan_score: 0,
    revenue_path: '',
    scout_summary: '',
    team1_notes: '',
    team1_decision: null,
    compliance: {},
    rep_type: '',
    commission: '',
    term_length: '',
    team2_notes: '',
    team2_decision: null,
    director_decision: null,
    portal_setup: false,
    technical_routing: false,
    warm_handoff: '',
    warm_handoff_confirmed: false,
    revenue_ytd: '0',
    revenue_projected: '0',
    last_contacted: '2026-08-01',
    application_id: 'app_aaliyah',
    application_status: 'sent',
    uploaded_docs: {},
    audit_log: [
      {
        user: 'Jordan Hayes',
        role: 'Scout',
        action: 'Created holding record',
        stage: 'holding_entry',
        ts: '2026-08-01T09:00:00Z',
      },
    ],
  },
  {
    id: 't9',
    name: 'Marcus Nguyen',
    stage: 'holding_entry',
    niches: [],
    scout_id: 'u1',
    created_at: '2026-07-28T15:20:00Z',
    social_handle: '@marcusnguyen',
    follower_count: '210K',
    er_pct: '3.8',
    platform: 'TikTok',
    location: 'Orange County, CA',
    pillar_scores: [0, 0, 0, 0, 0],
    pillar_rationales: ['', '', '', '', ''],
    jordan_score: 0,
    revenue_path: '',
    scout_summary: '',
    team1_notes: '',
    team1_decision: null,
    compliance: {},
    rep_type: '',
    commission: '',
    term_length: '',
    team2_notes: '',
    team2_decision: null,
    director_decision: null,
    portal_setup: false,
    technical_routing: false,
    warm_handoff: '',
    warm_handoff_confirmed: false,
    revenue_ytd: '0',
    revenue_projected: '0',
    last_contacted: '2026-08-01',
    application_id: 'app_marcus_n',
    application_status: 'in_progress',
    uploaded_docs: {},
    audit_log: [
      {
        user: 'Jordan Hayes',
        role: 'Scout',
        action: 'Created holding record',
        stage: 'holding_entry',
        ts: '2026-07-28T15:20:00Z',
      },
    ],
  },
  {
    id: 't10',
    name: 'Sofia Ramirez',
    stage: 'holding_entry',
    niches: ['Model', 'Influencer'],
    scout_id: 'u1',
    created_at: '2026-07-20T11:00:00Z',
    social_handle: '@sofiaramirez',
    follower_count: '780K',
    er_pct: '6.2',
    platform: 'Instagram',
    location: 'Chicago, IL',
    pillar_scores: [0, 0, 0, 0, 0],
    pillar_rationales: ['', '', '', '', ''],
    jordan_score: 0,
    revenue_path: '',
    scout_summary: 'Fashion/lifestyle creator — application incomplete (docs outstanding).',
    team1_notes: '',
    team1_decision: null,
    compliance: {},
    rep_type: '',
    commission: '',
    term_length: '',
    team2_notes: '',
    team2_decision: null,
    director_decision: null,
    portal_setup: false,
    technical_routing: false,
    warm_handoff: '',
    warm_handoff_confirmed: false,
    revenue_ytd: '0',
    revenue_projected: '0',
    last_contacted: '2026-08-01',
    application_id: 'app_sofia',
    application_status: 'submitted',
    uploaded_docs: {},
    audit_log: [
      {
        user: 'Sofia Ramirez',
        role: 'Prospect',
        action: 'Submitted application (incomplete)',
        stage: 'holding_entry',
        ts: '2026-07-25T20:00:00Z',
      },
    ],
  },
  {
    id: 't11',
    name: 'Jamal Washington',
    stage: 'holding_entry',
    niches: ['Athlete', 'Influencer'],
    scout_id: 'u1',
    created_at: '2026-07-10T13:00:00Z',
    social_handle: '@jamalwash',
    follower_count: '920K',
    er_pct: '5.9',
    platform: 'YouTube',
    location: 'Washington, DC',
    pillar_scores: [0, 0, 0, 0, 0],
    pillar_rationales: ['', '', '', '', ''],
    jordan_score: 0,
    revenue_path: 'Secure a national training-series partnership and grow newsletter to 25k.',
    scout_summary:
      'Former D1 basketball player turned sports commentary and training content creator.',
    team1_notes: '',
    team1_decision: null,
    compliance: {
      legal_name: true,
      gov_id: true,
      dob: true,
      address: true,
      email_phone: true,
      tax_doc: true,
      banking: true,
      social_ownership: true,
    },
    rep_type: '',
    commission: '',
    term_length: '',
    team2_notes: '',
    team2_decision: null,
    director_decision: null,
    portal_setup: false,
    technical_routing: false,
    warm_handoff: '',
    warm_handoff_confirmed: false,
    revenue_ytd: '0',
    revenue_projected: '0',
    last_contacted: '2026-08-01',
    application_id: 'app_jamal',
    application_status: 'submitted',
    uploaded_docs: {},
    audit_log: [
      {
        user: 'Jamal Washington',
        role: 'Prospect',
        action: 'Submitted application — auto-created holding record',
        stage: 'holding_entry',
        ts: '2026-07-18T16:40:00Z',
      },
    ],
  },
  {
    id: 't12',
    name: 'Elena Vasquez',
    stage: 'holding_entry',
    niches: ['Model', 'Influencer'],
    scout_id: 'u1',
    created_at: '2026-07-05T10:30:00Z',
    social_handle: '@elenavasquez',
    follower_count: '1.6M',
    er_pct: '9.1',
    platform: 'Instagram',
    location: 'Los Angeles, CA',
    pillar_scores: [0, 0, 0, 0, 0],
    pillar_rationales: ['', '', '', '', ''],
    jordan_score: 0,
    revenue_path: 'Book a national beauty campaign and expand TikTok to 500K.',
    scout_summary:
      'LA-based model and beauty creator known for clean glam tutorials and bilingual content.',
    team1_notes: '',
    team1_decision: null,
    compliance: {
      legal_name: true,
      gov_id: true,
      dob: true,
      address: true,
      email_phone: true,
      tax_doc: true,
      banking: true,
      social_ownership: true,
    },
    rep_type: '',
    commission: '',
    term_length: '',
    team2_notes: '',
    team2_decision: null,
    director_decision: null,
    portal_setup: false,
    technical_routing: false,
    warm_handoff: '',
    warm_handoff_confirmed: false,
    revenue_ytd: '0',
    revenue_projected: '0',
    last_contacted: '2026-08-01',
    application_id: 'app_elena',
    application_status: 'submitted',
    uploaded_docs: {},
    audit_log: [
      {
        user: 'Elena Vasquez',
        role: 'Prospect',
        action: 'Submitted application — auto-created holding record',
        stage: 'holding_entry',
        ts: '2026-07-12T19:15:00Z',
      },
    ],
  },
  {
    id: 't13',
    name: 'Tyler Brooks',
    stage: 'holding_entry',
    niches: ['Influencer', 'Actor'],
    scout_id: 'u1',
    created_at: '2026-07-15T09:00:00Z',
    social_handle: '@tylerbrooks',
    follower_count: '540K',
    er_pct: '7.4',
    platform: 'TikTok',
    location: 'Austin, TX',
    pillar_scores: [0, 0, 0, 0, 0],
    pillar_rationales: ['', '', '', '', ''],
    jordan_score: 0,
    revenue_path: 'Land two national commercial auditions through Nzinga.',
    scout_summary: 'Austin comedy creator with short-form sketches and commercial-acting credits.',
    team1_notes: '',
    team1_decision: null,
    compliance: {
      legal_name: true,
      gov_id: true,
      dob: true,
      address: true,
      email_phone: true,
      tax_doc: true,
      banking: true,
      social_ownership: true,
    },
    rep_type: '',
    commission: '',
    term_length: '',
    team2_notes: '',
    team2_decision: null,
    director_decision: null,
    portal_setup: false,
    technical_routing: false,
    warm_handoff: '',
    warm_handoff_confirmed: false,
    revenue_ytd: '0',
    revenue_projected: '0',
    last_contacted: '2026-08-01',
    application_id: 'app_tyler',
    application_status: 'submitted',
    uploaded_docs: {},
    audit_log: [
      {
        user: 'Tyler Brooks',
        role: 'Prospect',
        action: 'Submitted application — auto-created holding record',
        stage: 'holding_entry',
        ts: '2026-07-22T14:05:00Z',
      },
    ],
  },
  {
    id: 't14',
    name: 'Naomi Okonkwo',
    stage: 'holding_entry',
    niches: ['Model', 'Actor'],
    scout_id: 'u1',
    created_at: '2026-06-28T12:00:00Z',
    social_handle: '@naomiokonkwo',
    follower_count: '1.05M',
    er_pct: '8.0',
    platform: 'Instagram',
    location: 'Brooklyn, NY',
    pillar_scores: [0, 0, 0, 0, 0],
    pillar_rationales: ['', '', '', '', ''],
    jordan_score: 0,
    revenue_path: 'Secure exclusive representation and book fall campaign work.',
    scout_summary: 'Brooklyn-based model and emerging actor with runway and editorial experience.',
    team1_notes: '',
    team1_decision: null,
    compliance: {
      legal_name: true,
      gov_id: true,
      dob: true,
      address: true,
      email_phone: true,
      tax_doc: true,
      banking: true,
      social_ownership: true,
    },
    rep_type: '',
    commission: '',
    term_length: '',
    team2_notes: '',
    team2_decision: null,
    director_decision: null,
    portal_setup: false,
    technical_routing: false,
    warm_handoff: '',
    warm_handoff_confirmed: false,
    revenue_ytd: '0',
    revenue_projected: '0',
    last_contacted: '2026-08-01',
    application_id: 'app_naomi',
    application_status: 'submitted',
    uploaded_docs: {},
    audit_log: [
      {
        user: 'Naomi Okonkwo',
        role: 'Prospect',
        action: 'Submitted application — auto-created holding record',
        stage: 'holding_entry',
        ts: '2026-07-08T11:50:00Z',
      },
    ],
  },
  {
    id: 't15',
    name: 'Chris Patel',
    stage: 'holding_entry',
    niches: ['Influencer'],
    scout_id: 'u1',
    created_at: '2026-07-01T16:00:00Z',
    social_handle: '@chrispateltech',
    follower_count: '1.3M',
    er_pct: '4.2',
    platform: 'YouTube',
    location: 'San Jose, CA',
    pillar_scores: [0, 0, 0, 0, 0],
    pillar_rationales: ['', '', '', '', ''],
    jordan_score: 0,
    revenue_path: 'Negotiate exclusive consumer-tech representation with Nzinga.',
    scout_summary:
      'Tech and consumer-electronics reviewer with deep product analysis and live unboxings.',
    team1_notes: '',
    team1_decision: null,
    compliance: {
      legal_name: true,
      gov_id: true,
      dob: true,
      address: true,
      email_phone: true,
      tax_doc: true,
      banking: true,
      social_ownership: true,
    },
    rep_type: '',
    commission: '',
    term_length: '',
    team2_notes: '',
    team2_decision: null,
    director_decision: null,
    portal_setup: false,
    technical_routing: false,
    warm_handoff: '',
    warm_handoff_confirmed: false,
    revenue_ytd: '0',
    revenue_projected: '0',
    last_contacted: '2026-08-01',
    application_id: 'app_chris',
    application_status: 'submitted',
    uploaded_docs: {},
    audit_log: [
      {
        user: 'Chris Patel',
        role: 'Prospect',
        action: 'Submitted application — auto-created holding record',
        stage: 'holding_entry',
        ts: '2026-07-09T21:30:00Z',
      },
    ],
  },
] as Talent[]

export const TALENTS_SEED: Talent[] = talentsRaw.map((t, i) => ({
  ...t,
  account_number: formatAccountNumber(ACCOUNT_NUMBER_START + i),
}))

/** Minimal placeholder PDF used for complete submitted apps in seed/demo data. */
const SEED_DOC = 'data:application/pdf;base64,JVBERi0xLjQKJeLjz9MKMSAwIG9iago8PC9UeXBlL0NhdGFsb2cvUGFnZXMgMiAwIFI+PgplbmRvYmoK'

const completeSections = [
  'personal',
  'interests',
  'general',
  'influencing',
  'conflicts',
  'availability',
  'social',
  'id_verification',
  'final',
] as const

function completeSeedAppData(p: {
  first: string
  last: string
  dob: string
  phone: string
  email: string
  address?: string
  city: string
  state: string
  zip?: string
  handle: string
  platform: string
  followers: string
  er?: string
  niches: string
  bio: string
  achievements: string
  brands?: string
  goals90: string
  goals1y?: string
}) {
  const interests = p.niches
    .split(',')
    .map((s) => s.trim())
    .map((n) =>
      n === 'Model'
        ? 'Modeling'
        : n === 'Actor'
          ? 'Acting'
          : n === 'Athlete'
            ? 'Sports & Athletics'
            : n === 'Influencer'
              ? 'Influencing / Content Creation'
              : n,
    )
    .join(',')
  return {
    legal_first: p.first,
    legal_last: p.last,
    preferred_name: `${p.first} ${p.last}`,
    dob: p.dob,
    phone: p.phone,
    email: p.email,
    city: p.city,
    state: p.state,
    country: 'USA',
    current_market: `${p.city}, ${p.state}`,
    doc_profile_photo: SEED_DOC,
    doc_profile_photo_name: 'profile.jpg',
    doc_profile_photo_type: 'image/jpeg',
    representation_interests: interests || 'Influencing / Content Creation',
    experience_level: 'Experienced',
    about_yourself: p.bio,
    career_goals: p.goals90,
    proud_accomplishments: p.achievements,
    why_nzinga_interest: 'I want professional representation with Nzinga.',
    influencer_primary_platform: p.platform,
    influencer_handle: p.handle,
    influencer_content_categories: 'Lifestyle,Fashion',
    influencer_followers: p.followers,
    influencer_content_desc: p.bio,
    currently_represented: 'No',
    has_conflicting_obligations: 'No',
    work_markets: 'Local,National',
    willing_to_travel: 'Yes',
    currently_available: 'Yes',
    link_instagram: `https://instagram.com/${p.handle.replace('@', '')}`,
    doc_gov_id: SEED_DOC,
    doc_gov_id_name: 'Government_ID.pdf',
    doc_gov_id_type: 'application/pdf',
    why_represent: 'I believe Nzinga is the right partner for my career.',
    goals_1_2_years: p.goals1y || p.goals90,
    consent_truth: 'yes',
    consent_contact: 'yes',
    signature: `${p.first} ${p.last}`,
    signature_date: '2026-07-18',
  }
}

export const APPLICATIONS_SEED: ApplicationsMap = {
  app_kai: {
    id: 'app_kai',
    talent_id: 't4',
    access_code: 'KAI2026',
    company_code: 'NZG',
    talent_name: 'Kai Johnson',
    talent_email: 'kai@example.com',
    status: 'in_progress',
    created_at: '2026-05-18T10:00:00Z',
    last_saved: '2026-05-19T14:30:00Z',
    completed_sections: ['personal', 'interests'],
    data: {
      legal_first: 'Kai',
      legal_last: 'Johnson',
      preferred_name: 'Kai Johnson',
      dob: '2000-03-15',
      phone: '312-555-0199',
      email: 'kai@example.com',
      city: 'Chicago',
      state: 'IL',
      country: 'USA',
      current_market: 'Chicago, IL',
      representation_interests: 'Influencing / Content Creation',
      influencer_handle: '@kaij_music',
      influencer_primary_platform: 'TikTok',
      influencer_followers: '320K',
    },
  },
  app_aaliyah: {
    id: 'app_aaliyah',
    talent_id: 't8',
    access_code: 'AALI2026',
    company_code: 'NZG',
    talent_name: 'Aaliyah Brooks',
    talent_email: 'aaliyah.brooks@example.com',
    status: 'sent',
    created_at: '2026-08-01T09:05:00Z',
    last_saved: '2026-08-01T09:05:00Z',
    completed_sections: [],
    data: {},
  },
  app_marcus_n: {
    id: 'app_marcus_n',
    talent_id: 't9',
    access_code: 'MARC2026',
    company_code: 'NZG',
    talent_name: 'Marcus Nguyen',
    talent_email: 'marcus.nguyen@example.com',
    status: 'in_progress',
    created_at: '2026-07-28T15:25:00Z',
    last_saved: '2026-08-03T18:10:00Z',
    completed_sections: ['personal', 'interests'],
    data: {
      legal_first: 'Marcus',
      legal_last: 'Nguyen',
      preferred_name: 'Marcus Nguyen',
      dob: '1998-11-02',
      phone: '714-555-0288',
      email: 'marcus.nguyen@example.com',
      city: 'Costa Mesa',
      state: 'CA',
      country: 'USA',
      current_market: 'Costa Mesa, CA',
      representation_interests: 'Influencing / Content Creation',
      influencer_handle: '@marcusnguyen',
      influencer_primary_platform: 'TikTok',
      influencer_followers: '210K',
    },
  },
  app_sofia: {
    id: 'app_sofia',
    talent_id: 't10',
    access_code: 'SOFI2026',
    company_code: 'NZG',
    talent_name: 'Sofia Ramirez',
    talent_email: 'sofia.ramirez@example.com',
    status: 'submitted',
    created_at: '2026-07-20T11:05:00Z',
    last_saved: '2026-07-25T20:00:00Z',
    completed_sections: ['personal', 'interests', 'general', 'modeling', 'influencing'],
    data: {
      legal_first: 'Sofia',
      legal_last: 'Ramirez',
      preferred_name: 'Sofia Ramirez',
      dob: '1997-06-18',
      phone: '312-555-0344',
      email: 'sofia.ramirez@example.com',
      city: 'Chicago',
      state: 'IL',
      country: 'USA',
      current_market: 'Chicago, IL',
      representation_interests: 'Modeling,Influencing / Content Creation',
      experience_level: 'Experienced',
      about_yourself: 'Chicago-based fashion and lifestyle creator focused on accessible luxury and Latine culture.',
      career_goals: 'Land two mid-tier fashion partnerships and grow IG Reels by 20%.',
      proud_accomplishments: 'Featured in Vogue Mexico digital, 4 paid brand campaigns in 2025.',
      why_nzinga_interest: 'I want professional representation with Nzinga.',
      influencer_handle: '@sofiaramirez',
      influencer_primary_platform: 'Instagram',
      influencer_followers: '780K',
      influencer_content_categories: 'Fashion,Lifestyle',
      influencer_content_desc: 'Fashion and lifestyle content.',
      currently_represented: 'No',
      has_conflicting_obligations: 'No',
    },
  },
  app_jamal: {
    id: 'app_jamal',
    talent_id: 't11',
    access_code: 'JAMA2026',
    company_code: 'NZG',
    talent_name: 'Jamal Washington',
    talent_email: 'jamal.washington@example.com',
    status: 'submitted',
    created_at: '2026-07-10T13:00:00Z',
    last_saved: '2026-07-18T16:40:00Z',
    completed_sections: [...completeSections],
    data: completeSeedAppData({
      first: 'Jamal',
      last: 'Washington',
      dob: '1995-04-12',
      phone: '202-555-0411',
      email: 'jamal.washington@example.com',
      address: '1200 U St NW',
      city: 'Washington',
      state: 'DC',
      zip: '20009',
      handle: '@jamalwash',
      platform: 'YouTube',
      followers: '920K',
      er: '5.9',
      niches: 'Athlete,Influencer',
      bio: 'Former D1 basketball player turned sports commentary and training content creator.',
      achievements: '1.2M YouTube views on training series; Nike community event host 2025.',
      brands: 'Nike Community, Gatorade local, Under Armour affiliate',
      goals90: 'Secure a national training-series partnership and grow newsletter to 25k.',
      goals1y: 'Launch a signature training app with brand backing.',
    }),
  },
  app_elena: {
    id: 'app_elena',
    talent_id: 't12',
    access_code: 'ELEN2026',
    company_code: 'NZG',
    talent_name: 'Elena Vasquez',
    talent_email: 'elena.vasquez@example.com',
    status: 'submitted',
    created_at: '2026-07-05T10:30:00Z',
    last_saved: '2026-07-12T19:15:00Z',
    completed_sections: [...completeSections],
    data: completeSeedAppData({
      first: 'Elena',
      last: 'Vasquez',
      dob: '1999-09-03',
      phone: '213-555-0522',
      email: 'elena.vasquez@example.com',
      address: '840 S Spring St',
      city: 'Los Angeles',
      state: 'CA',
      zip: '90014',
      handle: '@elenavasquez',
      platform: 'Instagram',
      followers: '1.6M',
      er: '9.1',
      niches: 'Model,Influencer',
      bio: 'LA-based model and beauty creator known for clean glam tutorials and bilingual content.',
      achievements: 'Sephora squad finalist; 3 national beauty campaigns.',
      brands: 'Sephora, Fenty Beauty, Rare Beauty',
      goals90: 'Book a national beauty campaign and expand TikTok to 500K.',
      goals1y: 'Build a bilingual beauty brand incubator with Nzinga.',
    }),
  },
  app_tyler: {
    id: 'app_tyler',
    talent_id: 't13',
    access_code: 'TYLE2026',
    company_code: 'NZG',
    talent_name: 'Tyler Brooks',
    talent_email: 'tyler.brooks@example.com',
    status: 'submitted',
    created_at: '2026-07-15T09:00:00Z',
    last_saved: '2026-07-22T14:05:00Z',
    completed_sections: [...completeSections],
    data: completeSeedAppData({
      first: 'Tyler',
      last: 'Brooks',
      dob: '1996-01-27',
      phone: '512-555-0633',
      email: 'tyler.brooks@example.com',
      address: '901 Congress Ave',
      city: 'Austin',
      state: 'TX',
      zip: '78701',
      handle: '@tylerbrooks',
      platform: 'TikTok',
      followers: '540K',
      er: '7.4',
      niches: 'Influencer,Actor',
      bio: 'Austin comedy creator with short-form sketches and commercial-acting credits.',
      achievements: 'SAG-AFTRA eligible; 3 national commercial bookings.',
      brands: 'Indeed, DoorDash, local tourism board',
      goals90: 'Land two national commercial auditions through Nzinga.',
      goals1y: 'Transition into series regular comedy roles.',
    }),
  },
  app_naomi: {
    id: 'app_naomi',
    talent_id: 't14',
    access_code: 'NAOM2026',
    company_code: 'NZG',
    talent_name: 'Naomi Okonkwo',
    talent_email: 'naomi.okonkwo@example.com',
    status: 'submitted',
    created_at: '2026-06-28T12:00:00Z',
    last_saved: '2026-07-08T11:50:00Z',
    completed_sections: [...completeSections],
    data: completeSeedAppData({
      first: 'Naomi',
      last: 'Okonkwo',
      dob: '1994-12-08',
      phone: '347-555-0744',
      email: 'naomi.okonkwo@example.com',
      address: '210 Bedford Ave',
      city: 'Brooklyn',
      state: 'NY',
      zip: '11249',
      handle: '@naomiokonkwo',
      platform: 'Instagram',
      followers: '1.05M',
      er: '8.0',
      niches: 'Model,Actor',
      bio: 'Brooklyn-based model and emerging actor with runway and editorial experience.',
      achievements: 'NYFW runway 2024–25; guest role on streaming drama.',
      brands: 'Reformation, Madewell, MAC Cosmetics',
      goals90: 'Secure exclusive representation and book fall campaign work.',
      goals1y: 'Build a dual modeling/acting slate with premium brands.',
    }),
  },
  app_chris: {
    id: 'app_chris',
    talent_id: 't15',
    access_code: 'CHRI2026',
    company_code: 'NZG',
    talent_name: 'Chris Patel',
    talent_email: 'chris.patel@example.com',
    status: 'submitted',
    created_at: '2026-07-01T16:00:00Z',
    last_saved: '2026-07-09T21:30:00Z',
    completed_sections: [...completeSections],
    data: completeSeedAppData({
      first: 'Chris',
      last: 'Patel',
      dob: '1993-07-21',
      phone: '408-555-0855',
      email: 'chris.patel@example.com',
      address: '333 W San Carlos St',
      city: 'San Jose',
      state: 'CA',
      zip: '95110',
      handle: '@chrispateltech',
      platform: 'YouTube',
      followers: '1.3M',
      er: '4.2',
      niches: 'Influencer',
      bio: 'Tech and consumer-electronics reviewer with deep product analysis and live unboxings.',
      achievements: 'CES creator floor 2025; partnered with two Tier-1 OEMs.',
      brands: 'Samsung, Anker, Logitech',
      goals90: 'Negotiate exclusive consumer-tech representation with Nzinga.',
      goals1y: 'Launch a paid membership community and brand studio.',
    }),
  },
}
