export const TALENT_TYPES = ['Modeling', 'Acting', 'Influencing', 'Sports'] as const
export type TalentType = (typeof TALENT_TYPES)[number]

/** Staff-maintained roster sheet. Application answers only prefill empty fields. */
export interface TalentUdf {
  stageName: string
  talentTypes: TalentType[]
  talentStatus: string
  representationType: string
  representationStart: string
  representationEnd: string
  assignedAgent: string
  assignedManager: string
  talentTier: string
  careerGoals: string
  preferredContact: string
  emergencyName: string
  emergencyRelationship: string
  emergencyPhone: string
  emergencyEmail: string
  contractType: string
  contractStatus: string
  contractStart: string
  contractEnd: string
  renewalDate: string
  commissionRate: string
  managementFee: string
  exclusivity: string
  exclusivityCategory: string
  contractNotes: string
  availabilityStatus: string
  unavailableStart: string
  unavailableEnd: string
  preferredLocations: string
  travelInternational: string
  minBookingRate: string
  preferredJobTypes: string
  bookingNotes: string
  paymentEntity: string
  businessName: string
  w9Status: string
  paymentMethod: string
  financialCommissionRate: string
  paymentTerms: string
  paymentNotes: string
  govIdType: string
  govIdExpiration: string
  passportExpiration: string
  workAuth: string
  workAuthExpiration: string
  unionGuild: string
  licenseCert: string
  licenseExpiration: string
  preferredBrandCategories: string
  restrictedBrandCategories: string
  currentPartnerships: string
  brandExclusivity: string
  usageRights: string
  campaignCategory: string
  preferredAirport: string
  travelPreferences: string
  airlineHotel: string
  dietary: string
  transportation: string
  endReason: string
  terminationDate: string
  outstandingBookings: string
  outstandingPayments: string
  outstandingCommissions: string
  finalBalance: string
  formerStatus: string
  finalNotes: string
  height: string
  weight: string
  clothingSize: string
  shoeSize: string
  hairColor: string
  eyeColor: string
  bust: string
  waist: string
  hips: string
  modelingCategory: string
  portfolioComp: string
  sagAftra: string
  actingCategory: string
  actingReel: string
  actingExperience: string
  actingTraining: string
  specialSkills: string
  languages: string
  accents: string
  primaryPlatform: string
  socialHandles: string
  totalFollowers: string
  totalSubscribers: string
  averageViews: string
  engagementRate: string
  contentCategory: string
  audienceDemographics: string
  rateCard: string
  mediaKit: string
  sport: string
  position: string
  team: string
  league: string
  division: string
  athleteStatus: string
  careerHighlights: string
  currentSponsors: string
  sponsorshipCategories: string
  nilStatus: string
}
